### ISSUE TITLE
New BM UI + Firefox: All Imports broken with plugin enabled

### ISSUE THREAD

**Issue by dmersiowsky** [ForkPoint/dwithease#18]
Hi, currently the Plugin needs to be disabled when importing anyting (Metadata, Catalog etc.)

When doing the import validation, the browser seems to be excessively polling something. I can see a lot of requests going to  `ViewCustomizationImport-ValidateFileRefresh`.

I eventually get logged out of BM, supposedly due to hitting some rate limit or something.

Disabling the Plugin solves the issue.

Didn't test with classic UI, but the new UI cannot be used with the plugin here.

This happens for me with Firefox v137.0 on MacOS.

Thanks for looking into it!

**Comment by danieldudin** [comment]
Hi, @dmersiowsky can you double-check if the issue is still there, or if it's fixed with version 4.5.0 ?
Thanks!

**Comment by dmersiowsky** [comment]
Hi, unfortunately it's still there. 
Should be reproducible as follows (I used a Sandbox):

- Head to Site Development > Import & Export
- Upload a file of your choice (can be any file, valid XML not needed)
- Head to Meta Data Import
- Select the uploaded file
- Click "Next"
- Enjoy the endless polling :-)

Network traffic looks like this:

![Image](https://github.com/user-attachments/assets/3172c087-444f-4222-b262-95447c29507a)

**Comment by danieldudin** [comment]
Hi @dmersiowsky The issue should now be resolved in Firefox with version 4.6.0, could you please confirm that it works fine now? Thanks!

**Comment by dmersiowsky** [comment]
Hi @danieldudin, tank you so much! I am no longer able to reproduce this issue.

**Comment by dmersiowsky** [comment]
Hey @danieldudin, I'm afraid the issue is back. I can isolate it to DWWithEase again.
I'm using Firefox 145.0.2 (aarch64).

Here's how to reproduce:

- Head to BM: Go to an import tool of your choide (e.g. Inventory Import)
- Select a File, click "next"
- You'll face an endless loop during validation
- Browser shows a constantly refreshing white Page
- Eventually you will be blocked by Cloudflare ("Ooops")

https://github.com/user-attachments/assets/8098cd29-47db-4f9a-9214-445420c20346
